# Generated by Django 3.2.8 on 2021-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
