# Generated by Django 3.2.8 on 2021-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0002_alter_spi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
